# Generated by Django 4.1.4 on 2023-06-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursedata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
