# Generated by Django 4.2.1 on 2023-06-02 17:41

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursedata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
