# Generated by Django 4.2.1 on 2023-06-02 17:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_coursedata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
