# Generated by Django 4.1.4 on 2023-06-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursedata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y-%m/%d/'),
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
