# Generated by Django 4.1.4 on 2023-06-06 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_course_students_course_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='isShowhome',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Course Adı ile aynı olsun!', max_length=50),
        ),
    ]
